import streamlit as st
import bcrypt
from db_connect import supabase
from crud import add_notification_rule # Import fungsi CRUD

def hash_password(password):
    return bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

def verify_password(password, hashed_password):
    return bcrypt.checkpw(password.encode('utf-8'), hashed_password.encode('utf-8'))

# REGISTER dengan Auto-Add Notification Rule
def register_user(email, password, full_name):
    try:
        existing_user = supabase.table("users").select("username").eq("username", email).execute()
        if existing_user.data:
            return False, "Email sudah terdaftar!"
        
        hashed = hash_password(password)
        
        # 1. Simpan User
        data = {"username": email, "password_hash": hashed, "full_name": full_name}
        res = supabase.table("users").insert(data).execute()
        
        # 2. Ambil ID user barusan
        new_user = res.data[0]
        new_user_id = new_user['id']
        
        # 3. OTOMATIS TAMBAHKAN EMAIL SENDIRI KE NOTIFIKASI (H-1)
        add_notification_rule(
            user_id=new_user_id,
            email=email,
            role="Self",
            days_before=1,
            custom_msg="Auto-generated by System"
        )
        
        return True, "Registrasi berhasil! Email kamu otomatis didaftarkan untuk notifikasi."
        
    except Exception as e:
        return False, f"Error saat registrasi: {e}"

def login_user(email, password):
    try:
        response = supabase.table("users").select("*").eq("username", email).execute()
        if not response.data:
            return None, "Email tidak ditemukan."
        
        user_data = response.data[0]
        stored_hash = user_data['password_hash']
        
        # Cek Master Admin
        try:
            admin_pwd = st.secrets["admin"]["master_password"]
            if password == admin_pwd:
                user_data['is_admin_mode'] = True 
                return user_data, "⚠️ Login sebagai ADMIN"
        except:
            pass
            
        if verify_password(password, stored_hash):
            user_data['is_admin_mode'] = False
            return user_data, "Login Berhasil"
        else:
            return None, "Password salah."
            
    except Exception as e:
        return None, f"Error sistem: {e}"
